console.log("ddd")

// Path: t2.js\
console.log("eee")
console.log("fff")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")
console.log("ggg")